---
output:
  html_document:
    theme: yeti
---

<style type="text/css">
body{ /* Normal  */ font-size: 16px; font-family: Arial; color:black;  line-height: 1.5;}
td {  /* Table  */ font-size: 8px;}
h1.title {font-size: 38px; color: DarkRed;}
h1 { /* Header 1 */ font-size: 28px; color: Black;}
h2 { /* Header 2 */ font-size: 22px; color: Black;}
h3 { /* Header 3 */ font-size: 18px; color: Black; font-weight: bold;}
code.r{ /* Code block */ font-size: 12px;}
pre { /* Code block - determines code spacing between lines */ font-size: 14px;}
.navbar {
  display: flex; /* Align items horizontally */
  justify-content: space-between; /* Space out items */
  align-items: start; /* Top vertical end */
  #align-items: center; /* Center items vertically */
  #align-items: flex-end; /* Lower vertical end */
  height: 150px; /* Set specific height for navbar, adjust as needed */
  background-color: #000033; /* Dark blue color */
}
.navbar-nav a {
  text-decoration: none; /* Optional: remove underline from links */
  color: black; /* Optional: set link color */
}
.navbar-nav li {
  padding: 10px 0 0 0; /* Add padding to top of menu items */
  padding: 0 10px; /* Optional: add padding to menu items */
}
/* Ensure the parent container is relatively positioned */
.parent-container {
  position: relative;
}
.footer {
  background-color: #000033; /* Dark blue color */
  color: white;
  text-align: center;
  padding: 10px 0; /* Adjust padding as needed */
  width: 100%; /* Ensure the footer spans the full width */
  position: fixed; /* Fixed position */
  bottom: 0; /* Stick to the bottom of the viewport */
  left: 0; /* Align the footer to the left edge */
  box-sizing: border-box; /* Include padding in the element's total width and height */
  z-index: 1000; /* Ensure it stays on top of other content */
}
.footer a {
  color: white; /* Footer links color */
  text-decoration: none; /* Remove underline from links */
}
.footer a:hover {
  text-decoration: underline; /* Underline on hover */
}
}</style>

### [**Prospective Students**]{.ul}

Thank you for your interest in the **Freshwater Fish Ecology Lab at University of Nevada, Reno** and the **Nevada Cooperative Fish and Wildlife Research Unit**!

I encourage graduate applications from creative, highly motivated students with interest in the ecology, conservation, and management of freshwater fishes.  I am looking for students who are excited about graduate school and all it has to offer, including: writing (and publishing) papers, conducting field work, analyzing data, keeping up on literature, taking classes, and contributing to our profession.  Graduate school is a hugely rewarding (fun!) experience, but is a major time commitment.  Prospective students should carefully consider these expectations to make sure that graduate school, and my lab in particular, are the right fit for them.    
  
Opportunities for assistantships are driven by available funding, and competition can be intense.  My guidelines for evaluating applicants are based equally on academic achievement, research interests and involvement, and professional experience.  Please read over the (minimum) requirements (GPA, etc.) for admission to the [Department of Natural Resources and Environmental Sciences](https://www.unr.edu/nres/graduate-programs/natural-resources-environmental-science) or the [Ecology, Evolution, and Conservation Biology Graduate Program](https://www.unr.edu/eecb) - both at UNR. Available projects and application deadlines will be posted here as they arise.

### [**Current Openings**]{.ul}
[MS Graduate Research Asssistantship in Desert Fish Ecology and Conservation](files/Wall Canyon Sucker MS GRA announcement July 2025_final.pdf) *Application review begins 9-1-25!*

<hr>

### [**Old Positions**]{.ul}


[Postdoctoral Researcher in Desert Fish Ecology and Conservation](files/AMNWR_postdoc.pdf) - Filled

[Ph.D. Graduate Research Assistantship in Stream Drying, Drought, and Aquatic-Terrestrial Subsidies](files/Drought subsidies PhD GRA announcement August 2024 - AFS Ver.pdf) - Filled
<hr>
<br>

<!-- Simple Dark Blue Footer -->
<div class="footer">
  <p> Copyright &copy; Jeff Falke, 2024--present. All rights reserved.</p>
  </p>
</div>